project:
  type: website
  output-dir: _site

website:
  title: "sagui"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/RafaelSdeSouza/sagui
  page-footer:
    left: "Part of the COIN Toolbox"
    right: "Built with Quarto"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
