// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// sagui_sparse_ward_cut_cpp
IntegerVector sagui_sparse_ward_cut_cpp(NumericMatrix features, IntegerMatrix nn_idx, int target_k);
RcppExport SEXP _sagui_sagui_sparse_ward_cut_cpp(SEXP featuresSEXP, SEXP nn_idxSEXP, SEXP target_kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type features(featuresSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type nn_idx(nn_idxSEXP);
    Rcpp::traits::input_parameter< int >::type target_k(target_kSEXP);
    rcpp_result_gen = Rcpp::wrap(sagui_sparse_ward_cut_cpp(features, nn_idx, target_k));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_sagui_sagui_sparse_ward_cut_cpp", (DL_FUNC) &_sagui_sagui_sparse_ward_cut_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_sagui(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
