# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sagui_sparse_ward_cut_cpp <- function(features, nn_idx, target_k) {
    .Call(`_sagui_sagui_sparse_ward_cut_cpp`, features, nn_idx, target_k)
}

